---
compiler:
- clang
- gcc
language: c
install: ./install.sh
script:
- "make -j$(nproc) -C llvm.build check-checkedc"
- "make -j$(nproc) -C llvm.build check-clang"

# Which OSs to build on
os:
- linux
- osx
sudo: required
dist: trusty

# What directories to cache
cache:
- ccache
- directories:
  - llvm
  - llvm.build
  - cmake
