---
compiler:
- clang
- gcc
language: c
install:
- ./install.sh
- ./checkout.sh
script:
# Build executables
- "make -j$(nproc) --no-print-directory -C llvm.build"
# Run tests (check-checkedc and check-clang)
- "make -j$(nproc) --no-print-directory -C llvm.build --keep-going check-checkedc check-clang"
# Run external tests
- "./llvm.lnt.ve/bin/lnt runtest nt -j$(nproc) --sandbox ./llvm.lnt.sandbox --cc ./llvm.build/bin/clang --test-suite ./llvm-test-suite --cflags -fcheckedc-extension"

# Which OSs to build on
os:
- linux
- osx
dist: trusty

# What directories to cache
cache:
- ccache
- directories:
  # Sources
  - llvm
  - llvm-test-suite
  - lnt
  # Build Dirs
  - llvm.build
  - llvm.lnt.sandbox
  # Utilities Install Dirs
  - llvm.lnt.ve
  - cmake

# For LNT
python: "2.7"
addons:
  apt:
    packages:
    - tcl
    - bison
    - zlib1g-dev

# We really don't care about building with gcc on osx
matrix:
  fast_finish: true
  exclude:
  - compiler: gcc
    os: osx
